// Package extratime is an extra time package for unmarshalling and marshalling json and xml.
package extratime

// This file is auto-generated by internal/gen.go. DO NOT EDIT.
//go:generate go run internal/gen.go
